image: ubuntu:latest

stages:
   - ftp-deploy

deploy:master:
    only:
        - master
    stage: ftp-deploy
    script:
        - apt-get update
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client lftp -y )'
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        - rm -Rf .git
        - rm -Rf .gitlab-ci.yml
        - rm -Rf .gitignore
        - lftp sftp://$DEPLOY_LOGIN:$DEPLOY_PASSWORD@ftp.cluster021.hosting.ovh.net -e "mirror -e --ignore-time -R ./ /home/pleaseopvc//please-open-it/playground/; quit"

